# Generated by Django 4.0.4 on 2022-04-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_myapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='url',
            field=models.CharField(default='/airpollution', max_length=20),
            preserve_default=False,
        ),
    ]
